### PR TITLE
Made library work when internet is not connected

### PR DESCRIPTION
**Pull request by evaherrada**
In my dorm, there isn't really any way to connect my MatrixPortal to the internet (VT uses an enterprise network). I still wanted to make use of this library, so I added a new parameter to the matrixportal constructor that lets you specify when you don't want to connect to internet. It would be really great if someone could make sure this still works when you're connecting to internet, since that's not something I can test

### CODE REVIEW

**Comment by dglaude** [comment]
I am very much interested into this kind of option.
Many Matrix Portal learn guide could work on an M4+Matrix FeatherWing (maybe adding RTC for clock related guide).
Anything where request is not mandatory (or could be replaced by RTC).
I adapted my copy of this library for that purpose (and for the wiring of my 64x64 matrix).

**Comment by makermelissa** [comment]
Hi, thanks for this PR. I'm trying to understand the main functions you would like out of the top level matrixportal library (which was intended to tie the network and graphics stuff together) that don't use network? Since this PR goes against the intention of this class, I would like to understand your needs better (both @dherrada and @dglaude). 

Most likely the functions you require should probably be moved down to the graphics layer, which is the correct approach and then you could just use that. It would result in less memory usage as well.

**Comment by makermelissa** [comment]
Also, if it's helpful, here's a diagram of the layout of the library:
MatrixPortal

**Comment by PaintYourDragon** [comment]
I’ve been using just the Matrix side of MatrixPortal (see Creature Eyes guide) as-is, doesn’t require invoking Network.

**Comment by evaherrada** [comment]
@PaintYourDragon Thanks, I'll take a look at that.

**Comment by evaherrada** [comment]
@makermelissa Ah, ok. That makes sense.

**Pull request closed without merging**
