### PR TITLE
Add use-wifi param

### LINKED ISSUE #85: Add BLE support to the library
I have a feedback item with this:

> Matrixportal code for LED matrix does not coexist with BLE. I used the sample BLE code for other projects and it works well. But when i try to integrate it with this code, it fails.
> ```
> matrixportal = MatrixPortal(status_neopixel=board.NEOPIXEL, debug=False)
> ```
> The error is:
> ```
> Traceback (most recent call last):
> File "code.py", line 60, in
> File "adafruit_matrixportal/matrixportal.py", line 110, in __init__
> File "adafruit_matrixportal/network.py", line 66, in __init__
> File "adafruit_portalbase/wifi_coprocessor.py", line 57, in __init__
> ValueError: ESP_BUSY in use
> ```

I'm not sure if the Library will work fine if the esp object is initialized first and passed in or if any changes would be necessary. Either way, it makes sense that we should have an example.

### PR DESCRIPTION
**Pull request by justmobilize**
This fixes #85 by allowing the user to specify they don't want to use WiFi. A later PR could happen that enables Bluetooth.

### CODE REVIEW

**Comment by rebtop** [comment]
Justin,  Yes,  Please let me know when i can try it.

**Comment by justmobilize** [comment]
@rebtop you can download the files from here: https://github.com/justmobilize/Adafruit_CircuitPython_MatrixPortal/tree/add-use-wifi-param and replace what you have in `lib/adafruit_matrixportal` with what's in the `adafruit_matrixportal` from the download.

Then when you create it add `use_wifi`:
```py
matrixportal = MatrixPortal(
    # what ever you have currently
    use_wifi=False,
)
```

**Comment by rebtop** [comment]
I will try it tomorrowSent from my iPhoneOn May 30, 2024, at 9:01 PM, Justin Myers ***@***.***> wrote:﻿
@rebtop you can download the files from here: https://github.com/justmobilize/Adafruit_CircuitPython_MatrixPortal/tree/add-use-wifi-param and replace what you have in lib/adafruit_matrixportal with what's in the adafruit_matrixportal from the download.
Then when you create it add use_wifi:
matrixportal = MatrixPortal(
    # what ever you have currently
    use_wifi=False,
)

**Comment by rebtop** [comment]
Justin
I downloaded 3 files. Matrix.py, matrixportal.py and network.py.
in which file does the code you gave belong?
In the matrixportal.py i see    if use_wifi:  .....
Can you give me the file and line number for reference?

**Comment by rebtop** [comment]
I am assuming you want this inserted in the code itself. I will try that.

**Comment by rebtop** [comment]
That change takes the incompatibility out of play. Now i will work on getting Ble to work.

**Comment by justmobilize** [comment]
@rebtop awesome!

**Comment by rebtop** [comment]
K   Ble is working with MatrixPortal code.
Justin,   great job

**Comment by justmobilize** [comment]
Awesome. If you are willing to share code, I can use it as a basis to build in Bluetooth support into MatrixPortal

**Review by dhalbert — APPROVED** [review]
Thanks @justmobilize for the PR and @rebtop for testing.

**Comment by rebtop** [comment]
Justin
Let me clean it up some  and I will send it to you.
From Bob Black.  Sent from my iPad

On Jun 1, 2024, at 10:53 PM, Dan Halbert ***@***.***> wrote:

﻿

Merged #97<https://github.com/adafruit/Adafruit_CircuitPython_MatrixPortal/pull/97> into main.

**Comment by rebtop** [comment]
I am cleaning up the code and will share it shortly

**Comment by rebtop** [comment]
Justin
Been away and finally have a short script for you that works
M4 Matrixportal code with WIFI
[m4_one_input_ble.docx](https://github.com/user-attachments/files/16076240/m4_one_input_ble.docx)

**Pull request merged**
