### PR TITLE
Ported over to use PortalBase

### PR DESCRIPTION
**Pull request by makermelissa**
A good chunk of the functionality was removed from here that is part of PortalBase. I tested this on a few examples (specifically scrolling quotes, weather, and halloween countdown) and all worked perfectly with no modifications. Some functionality was moved from Network to WiFi in the initialization because it was specific to the ESP32 Coprocessor and the requests library and shouldn't affect functionality, so no code modifications on examples or user code should be necessary.

### CODE REVIEW

**Comment by makermelissa** [comment]
After this PR is merged, some guide updates will need to be made. Mostly the MatrixPortal guide which shows that you'll also need the PortalBase and FakeRequests libraries and the Creating MatrixPortal Projects guide will need to be updated as the structure/layout will be different.

Please keep this in mind if merging while I'm out.

**Comment by makermelissa** [comment]
I'm back, so feel free to merge at any time. This might fix some of the issues that have opened up since.

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
didnt test!

**Comment by makermelissa** [comment]
Thanks!

**Comment by makermelissa** [comment]
MatrixPortal and MatrixPortal Projects guides are now updated to reflect the refactor.

**Pull request merged**
