### PR TITLE
adding RP2040

### PR DESCRIPTION
**Pull request by djecken**
adding RP2040

### CODE REVIEW

**Comment by djecken** [comment]
I think this PR failed on the black checks, should I try to rerun? @makermelissa

**Comment by makermelissa** [comment]
If you run pre-commit on your computer it should automatically fix it.

**Comment by djecken** [comment]
@makermelissa @ladyada I ran the tests again this morning but is still failing. How can I do a pre-commit on my computer? Thanks

**Comment by dhalbert** [comment]
> @makermelissa @ladyada I ran the tests again this morning but is still failing. How can I do a pre-commit on my computer? Thanks

We have a Learn page on that :slightly_smiling_face: :
https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code

**Comment by djecken** [comment]
@dhalbert Thanks for the help + link. I have install the tools for running pre-commit on my mac ran it. Looks like it's failed again on the black check. Not sure how shall I proceed? 
terminal-precommit

**Comment by dhalbert** [comment]
Did it leave the file reformatted or throw it away? If the former you can just commit again. Otherwise run `black` by hand and then try the commit agian.

**Comment by djecken** [comment]
@dhalbert Ah, yes looks like it was reformatted – I committed and waiting on checks now.

**Comment by djecken** [comment]
OK yay green checks ✅ this is ready to merge

**Review by makermelissa — APPROVED** [review]
Thank you! This looks great.

**Pull request merged**
